/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-02 16:54:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class B_005fO_0020bibiotece_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"3.png\" sizes=\"96x96\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"B_styl_info.css\" type=\"text/css\">\r\n");
      out.write("    <title>O bibliotece</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td align=\"center\"><img src=\"logo.jpg\" name=\"ksiazka\" align=\"left\" weight=\"90px\" height=\"50px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <h1>\r\n");
      out.write("        <center><u>Informacje o bibliotece </u></center>\r\n");
      out.write("    </h1>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"A_strona-gl.jsp\">Strona główna</a></li>\r\n");
      out.write("                <li><a href=\"B_O bibiotece.jsp\">O bibliotece</a></li>\r\n");
      out.write("                <li><a href=\"C_Kategorie książek.jsp\">Kategorie książek </a></li>\r\n");
      out.write("                <li><a href=\"D_Wypożyczenia.jsp\">Wypożyczane </a></li>\r\n");
      out.write("                <li><a href=\"E_Słownik pojęć.jsp\">Słownik pojęć bibliotecznych</a></li>\r\n");
      out.write("                <li><a href=\"F_personel.jsp\">Prersonel</a></li>\r\n");
      out.write("               <!-- <li><a href=\"G_login.jsp\">Logowanie</a></li>\r\n");
      out.write("                <li><a href=\"H_rejestracja.jsp\">Rejestracja</a></li>-->\r\n");
      out.write("                <li><a href= \"logout\">Wyloguj się</a></li>\r\n");
      out.write("                <li><a > ");
      out.print(session.getAttribute("email-login") );
      out.write(" </a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h2>Witamy w naszej naukowej bibliotece </h2>\r\n");
      out.write("    <h3>\"W bibliotece możemy odnaleźć drogę do mądrości przeszłych wieków i otworzyć drzwi do wiedzy dla przyszłych\r\n");
      out.write("        pokoleń.\"</h3>\r\n");
      out.write("    <img src=\"https://cdn.pixabay.com/photo/2017/07/02/09/03/books-2463779__340.jpg\" slt=\"zdjęcie\" style=\"float:left \"\r\n");
      out.write("        width=\"400px\" height=\"400px\">\r\n");
      out.write("    <p>Biblioteka naukowa to miejsce, w którym zgromadzone są setki tysięcy książek, artykułów, czasopism i innych\r\n");
      out.write("        publikacji naukowych. Nasza biblioteka oferuje bogaty wybór zasobów z wielu dziedzin, takich jak <i> biologia,\r\n");
      out.write("            chemia, matematyka, fizyka, inżynieria, informatyka i wiele innych. </i>Ale również posiada gatunki książek\r\n");
      out.write("        np. <i>Fantastyka,Science fiction,Powieść historyczna,Romans,Kryminał i thriller,Powieść młodzieżowa,Literatura\r\n");
      out.write("            dziecięca,Biografia i reportaż,Literatura obyczajowa,Horror</i></p>\r\n");
      out.write("\r\n");
      out.write("    <p>Nasi użytkownicy mają dostęp do najnowszych i najbardziej wartościowych publikacji naukowych, a także do narzędzi\r\n");
      out.write("        i programów edukacyjnych, które pomagają w prowadzeniu badań naukowych i rozwoju naukowego. Oferujemy również\r\n");
      out.write("        dostęp do baz danych i czasopism naukowych, dzięki czemu nasi użytkownicy mogą być na bieżąco z najnowszymi\r\n");
      out.write("        odkryciami naukowymi.</p>\r\n");
      out.write("\r\n");
      out.write("    <p>Nasza biblioteka posiada zespół doświadczonych pracowników, którzy chętnie pomagają w znalezieniu potrzebnych\r\n");
      out.write("        zasobów oraz w udzielaniu porad i wskazówek dotyczących korzystania z naszych zasobów. Zapewniamy również dostęp\r\n");
      out.write("        do strefy czytelniczej, gdzie nasi użytkownicy mogą korzystać z wygodnych miejsc do pracy oraz z bezpłatnego\r\n");
      out.write("        dostępu do Internetu.</p>\r\n");
      out.write("\r\n");
      out.write("    <p>Zapraszamy do naszej biblioteki naukowej, gdzie znajdziecie Państwo nie tylko bogate zasoby naukowe, ale także\r\n");
      out.write("        przyjazną atmosferę i profesjonalną obsługę.</p>\r\n");
      out.write("\r\n");
      out.write("    <h2>Historia naszej biblioteki</h2>\r\n");
      out.write("\r\n");
      out.write("    <img src=\"https://cdn.pixabay.com/photo/2017/08/07/19/07/books-2606859__340.jpg\" alt=\"zdjęcie \" width=\"600\"\r\n");
      out.write("        height=\"510\" style=\"float: right;\">\r\n");
      out.write("    <p>Nasza biblioteka naukowa została założona w 1950 roku przez grupę pasjonatów nauki z różnych dziedzin. Początkowo\r\n");
      out.write("        biblioteka mieściła się w niewielkim pomieszczeniu na terenie uniwersytetu, lecz szybko zaczęła rozwijać się i\r\n");
      out.write("        zyskiwać na popularności wśród studentów i pracowników naukowych.</p>\r\n");
      out.write("\r\n");
      out.write("    <p>W ciągu kolejnych dekad biblioteka rozbudowywała swoje zbiory i zapewniała coraz lepsze warunki pracy dla swoich\r\n");
      out.write("        użytkowników. W latach 80. XX wieku biblioteka przeniosła się do nowoczesnego budynku, który zaprojektowano\r\n");
      out.write("        specjalnie pod kątem potrzeb biblioteki naukowej. Nowy budynek zapewnił większą przestrzeń i nowoczesne\r\n");
      out.write("        rozwiązania technologiczne, które zwiększyły wygodę i efektywność korzystania z zasobów biblioteki.</p>\r\n");
      out.write("\r\n");
      out.write("    <p>W ciągu kolejnych lat biblioteka stała się jednym z wiodących centrów naukowych w kraju, z zasobami obejmującymi\r\n");
      out.write("        setki tysięcy książek, czasopism, artykułów i innych publikacji naukowych z różnych dziedzin. Biblioteka stała\r\n");
      out.write("        się miejscem, w którym odbywały się liczne konferencje, seminaria, wystawy i inne wydarzenia naukowe, które\r\n");
      out.write("        przyciągały naukowców z całego kraju i zagranicy.</p>\r\n");
      out.write("\r\n");
      out.write("    <p>Dziś nasza biblioteka naukowa jest w pełni zintegrowana z uniwersytetem, oferując najnowsze technologie i\r\n");
      out.write("        narzędzia edukacyjne dla studentów i pracowników naukowych. Mimo swojego bogatego dziedzictwa i tradycji,\r\n");
      out.write("        biblioteka stale się rozwija i dostosowuje do potrzeb użytkowników, aby zapewnić najwyższą jakość swoich usług i\r\n");
      out.write("        zasobów.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h2>Wydarzenia w naszej bibliotece</h2>\r\n");
      out.write("\r\n");
      out.write("    <img src=\"https://cdn.pixabay.com/photo/2017/11/24/10/43/ticket-2974645__340.jpg\" alt=\"zdjęcie \" width=\"500\"\r\n");
      out.write("        height=\"410\" style=\"float: left;\">\r\n");
      out.write("    <p>Nasza biblioteka naukowa to nie tylko zasoby naukowe, ale również miejsce organizowania wydarzeń naukowych dla\r\n");
      out.write("        naszych użytkowników. W ciągu roku organizujemy wiele różnych wydarzeń, takich jak konferencje, seminaria,\r\n");
      out.write("        wystawy i spotkania naukowe. Oto kilka naszych najbliższych wydarzeń:</p>\r\n");
      out.write("    <p>Konferencja naukowa - \"Nowe trendy w badaniach biomedycznych\"\r\n");
      out.write("        Data: 15-17 kwietnia 2023\r\n");
      out.write("        Opis: Konferencja skupiająca się na najnowszych badaniach w dziedzinie biomedycyny. W programie m.in. wykłady i\r\n");
      out.write("        panele dyskusyjne prowadzone przez wybitnych naukowców z kraju i zagranicy.</p>\r\n");
      out.write("\r\n");
      out.write("    <p>Wystawa naukowa - \"Odkrycia XXI wieku\"\r\n");
      out.write("        Data: 1-31 maja 2023\r\n");
      out.write("        Opis: Wystawa prezentująca najnowsze odkrycia naukowe i technologiczne, które miały miejsce w XXI wieku. Na\r\n");
      out.write("        wystawie będzie można zobaczyć m.in. modele kosmicznych sond, robotów oraz nowoczesne narzędzia laboratoryjne.\r\n");
      out.write("    </p>\r\n");
      out.write("    <p>Seminarium - \"Zastosowanie sztucznej inteligencji w badaniach naukowych\"\r\n");
      out.write("        Data: 20 maja 2023\r\n");
      out.write("        Opis: Seminarium poświęcone wykorzystaniu sztucznej inteligencji w badaniach naukowych. W programie m.in.\r\n");
      out.write("        wykłady i prezentacje przedstawiające najnowsze trendy i rozwiązania w tej dziedzinie.</p>\r\n");
      out.write("    <p>Spotkanie naukowe - \"Odkrywajmy tajemnice kosmosu\"\r\n");
      out.write("        Data: 10 czerwca 2023\r\n");
      out.write("        Opis: Spotkanie z wybitnym astronomem, podczas którego uczestnicy będą mieli okazję dowiedzieć się więcej o\r\n");
      out.write("        najnowszych odkryciach i badaniach kosmosu.</p>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>(c) 2023 Biblioteka Naukowa. Wszelkie prawa zastrzeżone.</p>\r\n");
      out.write("            <p>Adres: ul. Biblioteczna 1, 00-217 Warszawa Telefon: +48 123 456 789  E-mail: kontakt@bibliotekamiejska.pl.</p>\r\n");
      out.write("    \r\n");
      out.write("        </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
