/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-27 15:44:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class E_005fSłownik_0020pojęć_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"3.png\" sizes=\"96x96\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"E_styl_slownik.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"> <!-- do ikony użytkownika -->\r\n");
      out.write("\r\n");
      out.write("    <title>Słownik Pojęć</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td align=\"center\"><img src=\"logo.png\" name=\"ksiazka\" align=\"left\" weight=\"90px\" height=\"50px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <h1>\r\n");
      out.write("        <center><u>Słownik pojęć bibliotecznych </u></center>\r\n");
      out.write("    </h1>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("             <ul>\r\n");
      out.write("                <li class=\"znacznik\" ><a href=\"A_strona-gl.jsp\"><button class=\"pobierz\" >Strona główna</button></a></li>\r\n");
      out.write("                <li class=\"znacznik\" ><a href=\"B_O bibiotece.jsp\"><button class=\"pobierz\" >O bibliotece</button></a></li>\r\n");
      out.write("                <li  class=\"znacznik\"><a href=\"C_Kategorie-książek.jsp\"><button class=\"pobierz\" >Kategorie książek</button> </a></li>\r\n");
      out.write("                <!--   <li><a href=\"D_Wypożyczenia.jsp\"><button class=\"pobierz\" >Wypożyczane </a></li>-->\r\n");
      out.write("                <li class=\"znacznik\"><a href=\"E_Słownik pojęć.jsp\"><button class=\"pobierz\" >Słownik pojęć bibliotecznych</button></a></li>\r\n");
      out.write("                <li class=\"znacznik\"><a href=\"F_personel.jsp\"><button class=\"pobierz\" >Personel</button></a></li>\r\n");
      out.write("               <!-- <li class=\"znacznik\"><a href=\"G_login.jsp\">Logowanie</a></li>\r\n");
      out.write("                <li class=\"znacznik\"><a href=\"H_rejestracja.jsp\">Rejestracja</a></li>-->\r\n");
      out.write("                <li> <a > ");
      out.print(session.getAttribute("administrator") );
      out.write("</a><li>\r\n");
      out.write("                 <li><a href=\"info_o_koncie.jsp\"><i class=\"fa fa-user\"></i><button class=\"klik\" > ");
      out.print(session.getAttribute("email-login") );
      out.write("</button></a></li>\r\n");
      out.write("                <li  ><a href=\"#\" onclick=\"confirmLogout()\"><button class=\"pobierz\" >Wyloguj się</button></a></li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <h2>\"Biblioteka to skarbnica wiedzy, która otwiera drzwi do nieograniczonych możliwości poznawczych i kulturalnych.\"\r\n");
      out.write("    </h2>\r\n");
      out.write("    <h4>Hasła biblioteczne które warto znać: </h4>\r\n");
      out.write("<div class=\"opcje\">\r\n");
      out.write("    <div class=\"col1\">\r\n");
      out.write("        <a href=\"#1\">\r\n");
      out.write("            <li>Akapit</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#2\">\r\n");
      out.write("            <li>Akcydens</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#3\">\r\n");
      out.write("            <li>Almanach</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#4\">\r\n");
      out.write("            <li>Aneks</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#5\">\r\n");
      out.write("            <li>Antykwariat</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#6\">\r\n");
      out.write("            <li>Aparat naukowy wydawnictwa</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#7\">\r\n");
      out.write("            <li>Artykuł </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#8\">\r\n");
      out.write("            <li>Atlas</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#9\">\r\n");
      out.write("            <li>Autor</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#10\">\r\n");
      out.write("            <li>Baza danych </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#11\">\r\n");
      out.write("            <li>Bedeker</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#12\">\r\n");
      out.write("            <li>Beletrystyka</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#13\">\r\n");
      out.write("            <li>Bibliofilstwo</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#14\">\r\n");
      out.write("            <li>Bibliografia</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#15\">\r\n");
      out.write("            <li>Bibliografia osobowa</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#16\">\r\n");
      out.write("            <li>Bibliografia załącznikowa </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#17\">\r\n");
      out.write("            <li>Biblioteka </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#18\">\r\n");
      out.write("            <li>Biblioteka narodowa</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#19\">\r\n");
      out.write("            <li>Biblioteka publiczna </li>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col2\">\r\n");
      out.write("        <a href=\"#20\">\r\n");
      out.write("            <li>Biblioteka szkolna </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#21\">\r\n");
      out.write("            <li>Czasopismo</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#22\">\r\n");
      out.write("            <li>Czytelnia </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#23\">\r\n");
      out.write("            <li>Dublet</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#24\">\r\n");
      out.write("            <li>Dział czasopisma</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#25\">\r\n");
      out.write("            <li>Ekslibris</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#26\">\r\n");
      out.write("            <li>Encyklopedia</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#27\">\r\n");
      out.write("            <li>Errata</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#28\">\r\n");
      out.write("            <li>Format książki</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#29\">\r\n");
      out.write("            <li>Gazeta</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#30\">\r\n");
      out.write("            <li>Hasło</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#31\">\r\n");
      out.write("            <li>Ilustracja</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#32\">\r\n");
      out.write("            <li>Indeks </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#33\">\r\n");
      out.write("            <li>Katalog tytułowy</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#34\">\r\n");
      out.write("            <li>Książka</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#35\">\r\n");
      out.write("            <li>Księgarstwo</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#36\">\r\n");
      out.write("            <li>Magazyn</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#37\">\r\n");
      out.write("            <li>Nakład </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#38\">\r\n");
      out.write("            <li>Notatka</li>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col3\">\r\n");
      out.write("        <a href=\"#39\">\r\n");
      out.write("            <li>Odsyłacz</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#40\">\r\n");
      out.write("            <li>Okładka</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#41\">\r\n");
      out.write("            <li>Opis bibliograficzny</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#42\">\r\n");
      out.write("            <li>Papirus</li>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#43\">\r\n");
      out.write("            <li>Pismo</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#44\">\r\n");
      out.write("            <li>Prasa</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#45\">\r\n");
      out.write("            <li>Prawo autorskie</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#46\">\r\n");
      out.write("            <li>Pseudonim</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#47\">\r\n");
      out.write("            <li>Publicystyka</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#48\">\r\n");
      out.write("            <li>Rękopis</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#49\">\r\n");
      out.write("            <li>Słowa kluczowe </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#50\">\r\n");
      out.write("            <li>Spis treści</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#51\">\r\n");
      out.write("            <li>Tytulatura</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#52\">\r\n");
      out.write("            <li>Wolumen</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#53\">\r\n");
      out.write("            <li>Wstęp</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#54\">\r\n");
      out.write("            <li>Wydawca</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#55\">\r\n");
      out.write("            <li>Wydawnictwo ciągłe </li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#56\">\r\n");
      out.write("            <li>Zestawienie tematyczne</li>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#57\">\r\n");
      out.write("            <li>Zwój</li>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <h3>Opis pojęć:</h3>\r\n");
      out.write("    <p id=\"1\">Akapit – wcięcie przy lewym marginesie, wydzielające odrębną część całości treściowej</p>\r\n");
      out.write("    <p id=\"2\">Akcydens – druk okolicznościowy, użytkowy lub informacyjny (np.: ulotka, kalendarz, instrukcja,\r\n");
      out.write("        program,\r\n");
      out.write("        formularz, bilet, karta pocztowa, prospekt) nie będący książką ani czasopismem</p>\r\n");
      out.write("    <p id=\"3\">Almanach – rocznik zawierający kalendarium wzbogacone informacjami lub poradami, czasem krótkimi\r\n");
      out.write("        opowiadaniami\r\n");
      out.write("        oraz materiałami o charakterze kronikarskim lub antologia zawierająca materiały z jednej dziedziny sztuki\r\n");
      out.write("        lub\r\n");
      out.write("        nauki, których wspólną cechą jest czas powstawania</p>\r\n");
      out.write("    <p id=\"4\">Aneks – dodatek, załącznik uzupełniający tekst główny</p>\r\n");
      out.write("    <p id=\"5\">Antykwariat – sklep z antykami, np. dziełami sztuki, księgarnia specjalistyczna ze starymi\r\n");
      out.write("        publikacjami\r\n");
      out.write("    </p>\r\n");
      out.write("    <p id=\"6\">Aparat naukowy wydawnictwa – zespół elementów wydawnictwa (publikacji naukowej) stanowiących wykazanie\r\n");
      out.write("        źródłowych\r\n");
      out.write("        materiałów cytowanych, omawianych bądź wykorzystywanych przez autora. Należą do nich przypisy, bibliografia\r\n");
      out.write("        załącznikowa, aneksy, odnośniki do innych tekstów.</p>\r\n");
      out.write("    <p id=\"7\">Artykuł – utwór naukowy, publicystyczny, literacki, będący samodzielną częścią większych całości (np.\r\n");
      out.write("        czasopisma,\r\n");
      out.write("        wydawnictwa zbiorowego); z reguły omawia problem, wyprowadza wnioski i uogólnienia, zmierzając do\r\n");
      out.write("        udowodnienia\r\n");
      out.write("        postawionej tezy lub uzasadnienia postula tów. Rodzaje artykułów: wstępny, redakcyjny, dyskusyjny,\r\n");
      out.write("        polemiczny,\r\n");
      out.write("        okolicznościowy, popularnonaukowy.</p>\r\n");
      out.write("    <p id=\"8\">Atlas – zbiór map, planszy, tablic, ilustracji, wybranych tematycznie (np. atlas Europy) i wydanych w\r\n");
      out.write("        postaci\r\n");
      out.write("        luźnego kompletu, książki drukowanej lub programu multimedialnego</p>\r\n");
      out.write("    <p id=\"9\">Autor – twórca dzieła</p>\r\n");
      out.write("    <p id=\"10\">Baza danych – zbiór danych wraz z oprogramowaniem umożliwiającym ich wykorzystanie, przeszukiwanie z\r\n");
      out.write("        uwzględnieniem różnych kryteriów</p>\r\n");
      out.write("\r\n");
      out.write("    <p id=\"11\">Bedeker – książka, przewodnik dla turystów (nazwa pochodzi od nazwiska niemieckiego wydawcy – K.\r\n");
      out.write("        Baedekera\r\n");
      out.write("        –\r\n");
      out.write("        który od 1836 roku publikował w wielu językach popularne przewodniki)</p>\r\n");
      out.write("    <p id=\"12\">Beletrystyka –utwory literatury pięknej, głównie powieści, nowele, opowiadania</p>\r\n");
      out.write("    <p id=\"13\">Bibliofilstwo – zamiłowanie do zbierania książek, kolekcjonowania rzadkich i cennych druków</p>\r\n");
      out.write("    <p id=\"14\">Bibliografia –uporządkowany (np. alfabetycznie, chronologicznie) spis dokumentów dobranych według\r\n");
      out.write("        określonych\r\n");
      out.write("        kryteriów. Wyróżniamy bibliografię: adnotowaną, bieżącą, narodową, osobową, załącznikową.</p>\r\n");
      out.write("    <p id=\"15\" id=\"top\">Bibliografia osobowa – bibliografia rejestrująca utwory jednego autora lub książki o autorze\r\n");
      out.write("        i\r\n");
      out.write("        recenzje\r\n");
      out.write("        jego\r\n");
      out.write("        dzieł</p>\r\n");
      out.write("    <p id=\"16\">Bibliografia załącznikowa – bibliografia będąca spisem źródeł, które autor wykorzystał przy pisaniu\r\n");
      out.write("        utworu, pracy\r\n");
      out.write("        naukowej lub które poleca czytelnikowi jako związane z tematem pracy</p>\r\n");
      out.write("    <p id=\"17\">Biblioteka – instytucja powołana do gromadzenia, opracowywania, przechowywania i udostępniania\r\n");
      out.write("        materiałów\r\n");
      out.write("        bibliotecznych. Rodzaje bibliotek: publiczne, szkolne, naukowe, pedagogiczne. Pierwsze biblioteki powstawały\r\n");
      out.write("        od\r\n");
      out.write("        III w. p.n.e. w Egipcie, Chinach, Babilonii, Grecji i Rzymie. W Polsce pierwsze biblioteki katedralne\r\n");
      out.write("        powstały w\r\n");
      out.write("        XI w.; pierwsza biblioteka uniwersytecka – Biblioteka Jagielońska – została założona w XIV w.</p>\r\n");
      out.write("    <p id=\"18\">Biblioteka narodowa – biblioteka odpowiedzialna za gromadzenie, opracowywanie i trwałe przechowywanie\r\n");
      out.write("        pełnej\r\n");
      out.write("        produkcji wydawniczej państwa (kraju) oraz wydawnictw zagranicznych dotyczących państwa. Biblioteka narodowa\r\n");
      out.write("        w\r\n");
      out.write("        Polsce została powołana do życia w 1928 r.</p>\r\n");
      out.write("    <p id=\"19\">Biblioteka publiczna – biblioteka ogólnodostępna, posiada zbiory o charakterze uniwersalnym</p>\r\n");
      out.write("    <p id=\"20\">Biblioteka szkolna – biblioteka będąca częścią szkoły; prowadzi działalność informacyjną,\r\n");
      out.write("        pedagogiczną i\r\n");
      out.write("        wychowawczą</p>\r\n");
      out.write("    <p id=\"21\">Czasopismo – wydawnictwo periodyczne; tygodnik, dwutygodnik, miesięcznik, kwartalnik, półrocznik,\r\n");
      out.write("        rocznik. Ze\r\n");
      out.write("        względu na treść dzielą się na: popularnonaukowe, naukowe, społeczno-polityczne, społeczno-kulturalne,\r\n");
      out.write("        literackie, techniczne, itp.</p>\r\n");
      out.write("    <p id=\"22\">Czytelnia – odrębne pomieszczenie lub wydzielone miejsce w bibliotece przeznaczone do korzystania z\r\n");
      out.write("        księgozbioru\r\n");
      out.write("        podręcznego na miejscu</p>\r\n");
      out.write("    <p id=\"23\">Dublet – drugi albo dalszy egzemplarz książki w zbiorach bibliotecznych</p>\r\n");
      out.write("    <p id=\"24\">Dział czasopisma – stała część czasopisma wyodrębniona ze względu na tematykę, źródło informacji,\r\n");
      out.write("        gatunek\r\n");
      out.write("        dziennikarski, funkcje lub adresata; z reguły wyróżniony odrębnym elementem graficznym, często także tytułem\r\n");
      out.write("    </p>\r\n");
      out.write("    <p id=\"25\">Ekslibris – artystycznie skomponowany znak własnościowy książki z nazwiskiem i symbolicznym znakiem\r\n");
      out.write("        właściciela\r\n");
      out.write("        lub nazwą instytucji, odbity na kartce przyklejanej na wewnętrzną stronę okładki</p>\r\n");
      out.write("    <p id=\"26\">Encyklopedia – wydawnictwo zawierające zbiór wiadomości ze wszystkich dziedzin wiedzy lub jednej\r\n");
      out.write("        dziedziny,\r\n");
      out.write("        uporządkowanych najczęściej alfabetycznie</p>\r\n");
      out.write("    <p id=\"27\">Errata – wykaz błędów i pomyłek dostrzeżonych w trakcie druku lub bezpośrednio po jego zakończeniu,\r\n");
      out.write("        opublikowany\r\n");
      out.write("        najczęściej w postaci osobnej kartki</p>\r\n");
      out.write("    <p id=\"28\"> Format książki – wysokość grzbietu książki mierzona w centymetrach</p>\r\n");
      out.write("    <p id=\"29\">Gazeta – dziennik, wydawnictwo periodyczne ukazujące się co najmniej dwa razy w tygodniu, zawierające\r\n");
      out.write("        informacje\r\n");
      out.write("        o wydarzeniach aktualnych, interesujących szerokie kręgi czytelników</p>\r\n");
      out.write("    <p id=\"30\">Hasło – wyraz decydujący o zaszeregowaniu treści w słowniku, encyklopedii lub katalogu przedmiotowym\r\n");
      out.write("    </p>\r\n");
      out.write("    <p id=\"31\">Ilustracja – reprodukcja rysunku, wykresu mapy, fotografii, dzieła malarskiego itp. stanowiąca\r\n");
      out.write("        uzupełnienie\r\n");
      out.write("        tekstu</p>\r\n");
      out.write("    <p id=\"32\">Indeks – wykaz terminów dołączony do wydawnictwa, zawierający hasła występujące w tekście i miejsca,\r\n");
      out.write("        w\r\n");
      out.write("        którym\r\n");
      out.write("        dane hasło się znajduje; ułatwia szybkie docieranie do poszukiwanych w książce informacji</p>\r\n");
      out.write("    <p id=\"33\">Katalog tytułowy – zbiór kart katalogowych ułożonych alfabetycznie według tytułów dzieł</p>\r\n");
      out.write("    <p id=\"34\">Książka – dokument graficzny najczęściej w postaci kodeksu, o określonej liczbie stron, zawierający\r\n");
      out.write("        utrwaloną\r\n");
      out.write("        myśl ludzką</p>\r\n");
      out.write("    <p id=\"35\">Księgarstwo – dział handlu zajmujący się hurtową i detaliczną sprzedażą książek</p>\r\n");
      out.write("    <p id=\"36\"> Magazyn – czasopismo, w którym istotnym elementem jest warstwa ilustracyjna. Artykuły w magazynie są\r\n");
      out.write("        krótkie i\r\n");
      out.write("        łatwe w odbiorze.</p>\r\n");
      out.write("    <p id=\"37\">Nakład – liczba egzemplarzy jednego wydania opublikowanego utworu</p>\r\n");
      out.write("    <p id=\"38\">Notatka – krótki tekst, uwaga, spostrzeżenie zapisane w celu zapamiętania treści; może mieć formę\r\n");
      out.write("        cytatu,\r\n");
      out.write("        planu,\r\n");
      out.write("        streszczenia, konspektu, wyciągu</p>\r\n");
      out.write("    <p id=\"39\">Odsyłacz – zapis pomocniczy stosowany w bibliografiach, indeksach, encyklopediach, słownikach,\r\n");
      out.write("        prowadzący\r\n");
      out.write("        do\r\n");
      out.write("        określonego terminu</p>\r\n");
      out.write("    <p id=\"40\">Okładka – zasadnicza część oprawy wydawnictwa; zabezpiecza przed zniszczeniem oraz pełni funkcję\r\n");
      out.write("        informacyjną i\r\n");
      out.write("        ozdobną</p>\r\n");
      out.write("    <p id=\"41\">Opis bibliograficzny – uporządkowany według określonych zasad zespół danych o dokumencie służących do\r\n");
      out.write("        jego\r\n");
      out.write("        identyfikacji</p>\r\n");
      out.write("    <p id=\"42\">Papirus – roślina rosnąca w Egipcie, z której w starożytności produkowano materiał pisarski</p>\r\n");
      out.write("\r\n");
      out.write("    <p id=\"43\">Pismo – usystematyzowany zbiór znaków symbolicznych, obrazkowych, wyrazowych, sylabowych służący do\r\n");
      out.write("        graficznego\r\n");
      out.write("        zapisywania informacji i myśli</p>\r\n");
      out.write("    <p id=\"44\">Prasa – wszelkie publikacje periodyczne ukazujące się nie rzadziej niż raz do roku, a w szczególności\r\n");
      out.write("        gazety i\r\n");
      out.write("        czasopisma</p>\r\n");
      out.write("    <p id=\"45\">Prawo autorskie – przepisy prawne wydane z myślą o ochronie interesów twórców</p>\r\n");
      out.write("    <p id=\"46\">Pseudonim – zmyślone imię i nazwisko, przybrane np. przez pisarzy, poetów, artystów lub dziennikarzy\r\n");
      out.write("    </p>\r\n");
      out.write("    <p id=\"47\">Publicystyka – publiczna wypowiedź na aktualne tematy społeczne, kulturalne, polityczne, naukowe;\r\n");
      out.write("        stanowi\r\n");
      out.write("        jedną z\r\n");
      out.write("        podstawowych form działalności dziennikarskiej</p>\r\n");
      out.write("    <p id=\"48\">Rękopis – tekst napisany ręcznie; także tekst pierwotny autora</p>\r\n");
      out.write("    <p id=\"49\">Słowa kluczowe – słowa wybrane jako podstawa budowy katalogu przedmiotowego</p>\r\n");
      out.write("    <p id=\"50\">Spis treści – wykaz części składowych wydawnictwa; może zawierać takie elementy jak np. wstęp,\r\n");
      out.write("        rozdziały,\r\n");
      out.write("        podrozdziały, indeksy, przypisy, bibliografię załącznikową, ilustracje, tablice, mapy</p>\r\n");
      out.write("    <p id=\"51\">Tytulatura – ogół danych służących do identyfikacji wydawnictwa, umieszczonych w przypadku czasopisma\r\n");
      out.write("        i\r\n");
      out.write("        gazety na\r\n");
      out.write("        pierwszej stronie, w przypadku książki – na karcie tytułowej i w metryce</p>\r\n");
      out.write("    <p id=\"52\">Wolumen – pojedynczy oprawiony egzemplarz druku (książka)</p>\r\n");
      out.write("    <p id=\"53\">Wstęp – tekst umieszczony z reguły na początku utworu; napisany przez autora, wydawcę, tłumacza lub\r\n");
      out.write("        inną\r\n");
      out.write("        osobę;\r\n");
      out.write("        zawiera informacje dotyczące powstawania utworu oraz jego problematyki</p>\r\n");
      out.write("    <p id=\"54\">Wydawca – osoba odpowiedzialna za merytoryczne przygotowanie publikacj</p>\r\n");
      out.write("    <p id=\"55\">Wydawnictwo ciągłe – wydawnictwo o nieprzewidzianym z góry zakończeniu, ukazujące się w określonych\r\n");
      out.write("        odstępach\r\n");
      out.write("        czasu – np. periodyki, wydawnictwa seryjne i zbiorowe</p>\r\n");
      out.write("    <p id=\"56\">Zestawienie tematyczne – spis tematyczny, opracowanie zawierające bibliografię dokumentów na\r\n");
      out.write("        określony\r\n");
      out.write("        temat</p>\r\n");
      out.write("    <p id=\"57\">Zwój – najstarsza forma książki, znana od IV tysiąclecia p.n.e.</p>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"#\" title=\"Do góry!\" id=\"scroll-to-top\"><img\r\n");
      out.write("            src=\"https://cdn.pixabay.com/photo/2014/03/25/16/34/arrow-297439_960_720.png\" alt=\"strzałka do góry\"\r\n");
      out.write("            width=\"50px\" height=\"50px\"></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <span>(c) 2023 Biblioteka  Publiczna. Wszelkie prawa zastrzeżone.</span><br>\r\n");
      out.write("        <span>Telefon: +48 123 456 789 E-mail: kontakt@bibliotekamiejska.pl.\r\n");
      out.write("        </span>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("      <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function confirmLogout() {\r\n");
      out.write("        swal({\r\n");
      out.write("            title: \"Czy na pewno chcesz się wylogować?\",\r\n");
      out.write("            icon: \"warning\",\r\n");
      out.write("            buttons: [\"Anuluj\", \"Wyloguj się\"],\r\n");
      out.write("            dangerMode: true,\r\n");
      out.write("        }).then((willLogout) => {\r\n");
      out.write("            if (willLogout) {\r\n");
      out.write("                window.location.href = \"logout\";\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
