/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-15 10:53:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class F_005fpersonel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"F_personel.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"3.png\" sizes=\"96x96\" />\r\n");
      out.write("    <title>Personel</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td align=\"center\"><img src=\"logo.jpg\" name=\"ksiazka\" align=\"left\" weight=\"90px\" height=\"50px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <h1>\r\n");
      out.write("        <center><u>Personel biblioteki </u></center>\r\n");
      out.write("    </h1>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("             <ul>\r\n");
      out.write("                <li class=\"znacznik\" ><a href=\"A_strona-gl.jsp\"><button class=\"pobierz\" >Strona główna</button></a></li>\r\n");
      out.write("                <li class=\"znacznik\" ><a href=\"B_O bibiotece.jsp\"><button class=\"pobierz\" >O bibliotece</button></a></li>\r\n");
      out.write("                <li  class=\"znacznik\"><a href=\"C_Kategorie książek.jsp\"><button class=\"pobierz\">Kategorie książek</button></a></li>\r\n");
      out.write("                <!--   <li><a href=\"D_Wypożyczenia.jsp\"><button class=\"pobierz\" >Wypożyczane </a></li>-->\r\n");
      out.write("                <li class=\"znacznik\"><a href=\"E_Słownik pojęć.jsp\"><button class=\"pobierz\" >Słownik pojęć bibliotecznych</button></a></li>\r\n");
      out.write("                <li class=\"znacznik\"><a href=\"F_personel.jsp\"><button class=\"pobierz\" >Personel</button></a></li>\r\n");
      out.write("               <!-- <li class=\"znacznik\"><a href=\"G_login.jsp\">Logowanie</a></li>\r\n");
      out.write("                <li class=\"znacznik\"><a href=\"H_rejestracja.jsp\">Rejestracja</a></li>-->\r\n");
      out.write("                <li> <a > ");
      out.print(session.getAttribute("administrator") );
      out.write("</a><li>\r\n");
      out.write("                <li ><a > ");
      out.print(session.getAttribute("email-login") );
      out.write(" </a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li  ><a href=\"#\" onclick=\"confirmLogout()\"><button class=\"pobierz\" >Wyloguj się</button></a></li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <h1 id=\"cytat\">„Im bardziej gęstnieje mrok, tym jaśniej świecą książki.” – Stanisław Zieliński</h1>\r\n");
      out.write("\r\n");
      out.write("    <h1 id=\"Kadra\">Kadra </h1>\r\n");
      out.write("    <div>\r\n");
      out.write("        <div class=\"Personel\">\r\n");
      out.write("            <h3>dr hab. inż. Klaudia Wójcik, Dyrektor biblioteki </h3>\r\n");
      out.write("            <h3>dr hab. Anna Kowalska, Kierownik biblioteki </h3>\r\n");
      out.write("            <h4>mgr Paweł Nowak, bibliotekarz</h4>\r\n");
      out.write("            <h4>mgr Małgorzata Wiśniewska, bibliotekarz</h4>\r\n");
      out.write("            <h4>mgr inż. Karol Zawadzki, specjalista ds. informatyzacji biblioteki</h4>\r\n");
      out.write("            <h4>dr hab. Małgorzata Szymańska, konsultant naukowy biblioteki</h4>\r\n");
      out.write("            <h4>mgr Maria Jankowska, bibliotekarz</h4>\r\n");
      out.write("            <h4>dr hab. Marcin Kowalczyk, koordynator projektów naukowych biblioteki</h4>\r\n");
      out.write("            <h4>mgr Agnieszka Kwiatkowska, bibliotekarz młodszy</h4>\r\n");
      out.write("            <h4>mgr lic. Adam Słowik, archiwista biblioteczny</h4>\r\n");
      out.write("            <h4>dr inż. Janusz Wojciechowski, specjalista ds. technologii druku 3D w bibliotece</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"Kontakt\">\r\n");
      out.write("            <img src=\"https://cdn.pixabay.com/photo/2019/04/26/18/41/books-4158244__340.jpg\" alt=\"zdj\" height=\"250px \"\r\n");
      out.write("                width=\"500px\">\r\n");
      out.write("            <h3 id=\"kontakt-napis\">\r\n");
      out.write("                <center>Kontakt</center>\r\n");
      out.write("            </h3>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("	 <div>\r\n");
      out.write("   			 <h1>Formularz do wysłania pytań lub problemów napotkanych na naszej stronie </h1>\r\n");
      out.write("   			 \r\n");
      out.write("		<form class=\"kontakt\" action=\"https://api.sheetmonkey.io/form/uAqJFTu2v7ZeCxUxJrE6fA\" method=\"post\">\r\n");
      out.write("  			\r\n");
      out.write("  			\r\n");
      out.write("  			<input placeholder=\"Podaj imię\" type=\"text\" name=\"imie\"  autocomplete=\"off\">\r\n");
      out.write("  			<input  type=\"hidden\" name=\"email\" value=\" ");
      out.print( session.getAttribute("email-login") );
      out.write("\">\r\n");
      out.write("  			\r\n");
      out.write(" 			<!-- <input placeholder=\"podaj swój adres e-mail\" type=\"text\" name=\"email\" required pattern=\"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\" autocomplete=\"off\"> -->\r\n");
      out.write("  			\r\n");
      out.write("  			<textarea rows=\"5\" cols=\"21\" type=\"text\" name=\"opis\" required placeholder=\"Wpisz pytanie\"></textarea>	\r\n");
      out.write("  			<input type=\"hidden\" name=\"Created\" value=\"x-sheetmonkey-current-date-time\" ><br>\r\n");
      out.write("  			<input type=\"submit\" value=\"Wyślij\" >\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("	</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	function confirmLogout() {\r\n");
      out.write("		if (confirm(\"Czy na pewno chcesz się wylogować?\")) {\r\n");
      out.write("			window.location.href = \"logout\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("	$('.kontakt').submit(function() {\r\n");
      out.write("	\r\n");
      out.write("	alert(\"Dziękujemy za przesłanie swojej wiadomości. Skontaktujemy się z Tobą wkrótce.\");\r\n");
      out.write("\r\n");
      out.write("	  // zwrócenie wartości true, aby formularz mógł zostać wysłany\r\n");
      out.write("	  return true;\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>	\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("        \r\n");
      out.write("            <p id=\"kom\">Jeśli chodzi o pytanie do konkretnej osoby to prosimy kontaktować się przez wysłanie pytania w formularzu po wyżej, \r\n");
      out.write("             tylko wtedy na początku podać konkretnego spoecjalistę.</p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <span>(c) 2023 Biblioteka  Publiczna. Wszelkie prawa zastrzeżone.</span><br>\r\n");
      out.write("        <span>Telefon: +48 123 456 789. E-mail: infobiblio@interia.pl</span>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
