/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-27 15:06:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class info_005fo_005fkoncie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Informacje o użytkowniku</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"info_uz.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <header>\r\n");
      out.write("    <nav>\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li class=\"znacznik\"><a href=\"A_strona-gl.jsp\"><button class=\"pobierz\">Strona główna</button></a></li>\r\n");
      out.write("        <li class=\"znacznik\"><a href=\"B_O bibiotece.jsp\"><button class=\"pobierz\">O bibliotece</button></a></li>\r\n");
      out.write("        <li class=\"znacznik\"><a href=\"C_Kategorie-książek.jsp\"><button class=\"pobierz\">Kategorie książek</button></a></li>\r\n");
      out.write("        <!--   <li><a href=\"D_Wypożyczenia.jsp\"><button class=\"pobierz\" >Wypożyczane </a></li>-->\r\n");
      out.write("        <li class=\"znacznik\"><a href=\"E_Słownik pojęć.jsp\"><button class=\"pobierz\">Słownik pojęć bibliotecznych</button></a></li>\r\n");
      out.write("        <li class=\"znacznik\"><a href=\"F_personel.jsp\"><button class=\"pobierz\">Personel</button></a></li>\r\n");
      out.write("        <!-- <li class=\"znacznik\"><a href=\"G_login.jsp\">Logowanie</a></li>\r\n");
      out.write("        <li class=\"znacznik\"><a href=\"H_rejestracja.jsp\">Rejestracja</a></li>-->\r\n");
      out.write("       \r\n");
      out.write("        <li  ><a href=\"#\" onclick=\"confirmLogout()\"><button class=\"pobierz\" >Wyloguj się</button></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h1>Twoje Dane</h1>\r\n");
      out.write("    <div class=\"user-info\">\r\n");
      out.write("      <div class=\"user-details\">\r\n");
      out.write("        <h2>Imie: ");
      out.print(session.getAttribute("aimie") );
      out.write("</h2>\r\n");
      out.write("        <h2>Nazwisko: ");
      out.print(session.getAttribute("anazwisko") );
      out.write("</h2>\r\n");
      out.write("        <p>Rola: ");
      out.print(session.getAttribute("administrator") );
      out.write("</p>\r\n");
      out.write("        <p>Email: ");
      out.print(session.getAttribute("email-login") );
      out.write("</p>\r\n");
      out.write("        <a href=\"forgotPassword2.jsp\"><button class=\"klik\">Jeśli chcesz zmienić hasło to kliknij tu</button></a>\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    	\r\n");
      out.write("    	function confirmLogout() {\r\n");
      out.write("    		if (confirm(\"Czy na pewno chcesz się wylogować?\")) {\r\n");
      out.write("    			window.location.href = \"logout\";\r\n");
      out.write("    		}\r\n");
      out.write("    	}\r\n");
      out.write("  \r\n");
      out.write("    	</script>\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
